/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    2023.1.1.200.1
    Soft IP Version: 1.8.0
    2023 10 02 17:49:00
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module PLL_1 (clki_i, rstn_i, clkop_o, clkos_o, clkos2_o, lock_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  clki_i;
    input  rstn_i;
    output  clkop_o;
    output  clkos_o;
    output  clkos2_o;
    output  lock_o;
endmodule