/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    2023.1.0.43.3
    Soft IP Version: 1.1.1
    2023 10 01 02:06:09
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module DDR3_PHY_2 (clk_i, eclk_i, clk_stable_i, dqsbuf_pause_i, ddr_rst_i,
    update_done_i, sclk_o, dll_update_o, phy_init_act_o, wl_act_o, wl_err_o,
    rt_err_o, rst_cntr_ready_o, csm_ready_o, dfi_rst_n_i, dfi_addr_i,
    dfi_bank_i, dfi_cas_n_i, dfi_cke_i, dfi_cs_n_i, dfi_odt_i, dfi_ras_n_i,
    dfi_we_n_i, dfi_wrdata_i, dfi_wrdataen_i, dfi_wrdata_mask_i,
    dfi_init_start_i, dfi_rddata_o, dfi_init_complete_o, dfi_rddata_valid_o,
    em_ddr_rst_n_o, em_ddr_clk_o, em_ddr_cke_o, em_ddr_addr_o, em_ddr_ba_o,
    em_ddr_cs_n_o, em_ddr_odt_o, em_ddr_cas_n_o, em_ddr_ras_n_o, em_ddr_we_n_o,
    em_ddr_dm_o, em_ddr_dqs_io, em_ddr_data_io)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  clk_i;
    input  eclk_i;
    input  clk_stable_i;
    input  dqsbuf_pause_i;
    input  ddr_rst_i;
    input  update_done_i;
    output  sclk_o;
    output  dll_update_o;
    output  phy_init_act_o;
    output  wl_act_o;
    output  wl_err_o;
    output  rt_err_o;
    output  rst_cntr_ready_o;
    output  csm_ready_o;
    input  dfi_rst_n_i;
    input  [13:0]  dfi_addr_i;
    input  [2:0]  dfi_bank_i;
    input  dfi_cas_n_i;
    input  [0:0]  dfi_cke_i;
    input  [0:0]  dfi_cs_n_i;
    input  [0:0]  dfi_odt_i;
    input  dfi_ras_n_i;
    input  dfi_we_n_i;
    input  [63:0]  dfi_wrdata_i;
    input  dfi_wrdataen_i;
    input  [7:0]  dfi_wrdata_mask_i;
    input  dfi_init_start_i;
    output  [63:0]  dfi_rddata_o;
    output  dfi_init_complete_o;
    output  dfi_rddata_valid_o;
    output  em_ddr_rst_n_o;
    output  [0:0]  em_ddr_clk_o;
    output  [0:0]  em_ddr_cke_o;
    output  [13:0]  em_ddr_addr_o;
    output  [2:0]  em_ddr_ba_o;
    output  [0:0]  em_ddr_cs_n_o;
    output  [0:0]  em_ddr_odt_o;
    output  em_ddr_cas_n_o;
    output  em_ddr_ras_n_o;
    output  em_ddr_we_n_o;
    output  [1:0]  em_ddr_dm_o;
    inout  [1:0]  em_ddr_dqs_io;
    inout  [15:0]  em_ddr_data_io;
endmodule