/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    2023.1.0.43.3
    Soft IP Version: 1.4.2
    2023 10 01 02:06:06
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module DDR3_MC_2 (clk_i, rst_n_i, mem_rst_n_i, init_start_i, cmd_i, addr_i,
    cmd_burst_cnt_i, cmd_valid_i, write_data_i, data_mask_i, cmd_rdy_o,
    datain_rdy_o, init_done_o, rt_err_o, wl_err_o, read_data_o,
    read_data_valid_o, sclk_o, clocking_good_o, em_ddr_data_io,
    em_ddr_reset_n_o, em_ddr_dqs_io, em_ddr_dm_o, em_ddr_clk_o, em_ddr_cke_o,
    em_ddr_ras_n_o, em_ddr_cas_n_o, em_ddr_we_n_o, em_ddr_cs_n_o, em_ddr_odt_o,
    em_ddr_addr_o, em_ddr_ba_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  clk_i;
    input  rst_n_i;
    input  mem_rst_n_i;
    input  init_start_i;
    input  [3:0]  cmd_i;
    input  [27:0]  addr_i;
    input  [4:0]  cmd_burst_cnt_i;
    input  cmd_valid_i;
    input  [255:0]  write_data_i;
    input  [31:0]  data_mask_i;
    output  cmd_rdy_o;
    output  datain_rdy_o;
    output  init_done_o;
    output  rt_err_o;
    output  wl_err_o;
    output  [255:0]  read_data_o;
    output  read_data_valid_o;
    output  sclk_o;
    output  clocking_good_o;
    inout  [31:0]  em_ddr_data_io;
    output  em_ddr_reset_n_o;
    inout  [3:0]  em_ddr_dqs_io;
    output  [3:0]  em_ddr_dm_o;
    output  [0:0]  em_ddr_clk_o;
    output  [0:0]  em_ddr_cke_o;
    output  em_ddr_ras_n_o;
    output  em_ddr_cas_n_o;
    output  em_ddr_we_n_o;
    output  [0:0]  em_ddr_cs_n_o;
    output  [0:0]  em_ddr_odt_o;
    output  [14:0]  em_ddr_addr_o;
    output  [2:0]  em_ddr_ba_o;
endmodule