/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    2023.1.0.43.3
    Soft IP Version: 1.6.0
    2023 10 01 02:06:15
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module MIPI_DPHY_2 (sync_clk_i, sync_rst_i, lmmi_clk_i, lmmi_resetn_i,
    lmmi_wdata_i, lmmi_wr_rdn_i, lmmi_offset_i, lmmi_request_i, lmmi_ready_o,
    lmmi_rdata_o, lmmi_rdata_valid_o, hs_tx_en_i, hs_tx_data_i,
    hs_tx_data_en_i, lp_tx_en_i, lp_tx_data_p_i, lp_tx_data_n_i,
    lp_tx_data_en_i, lp_tx_clk_p_i, lp_tx_clk_n_i, clk_p_io, clk_n_io,
    data_p_io, data_n_io, usrstdby_i, pd_dphy_i, txclk_hsgate_i, pll_lock_o,
    clk_byte_o, ready_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  sync_clk_i;
    input  sync_rst_i;
    input  lmmi_clk_i;
    input  lmmi_resetn_i;
    input  [3:0]  lmmi_wdata_i;
    input  lmmi_wr_rdn_i;
    input  [4:0]  lmmi_offset_i;
    input  lmmi_request_i;
    output  lmmi_ready_o;
    output  [3:0]  lmmi_rdata_o;
    output  lmmi_rdata_valid_o;
    input  hs_tx_en_i;
    input  [31:0]  hs_tx_data_i;
    input  hs_tx_data_en_i;
    input  lp_tx_en_i;
    input  [3:0]  lp_tx_data_p_i;
    input  [3:0]  lp_tx_data_n_i;
    input  lp_tx_data_en_i;
    input  lp_tx_clk_p_i;
    input  lp_tx_clk_n_i;
    inout  clk_p_io;
    inout  clk_n_io;
    inout  [3:0]  data_p_io;
    inout  [3:0]  data_n_io;
    input  usrstdby_i;
    input  pd_dphy_i;
    input  txclk_hsgate_i;
    output  pll_lock_o;
    output  clk_byte_o;
    output  ready_o;
endmodule